global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "services"
    static_configs:
      - targets:
          - "service-a:5000"
          - "service-b:5001"
  - job_name: 'ebpf'
    static_configs:
      - targets: ['localhost:9100']
